### PR TITLE
deleted xrfi.py and metrics.py

### PR DESCRIPTION
**Pull request by SaulAryehKohn**
Which have been moved to the `HERA-Team/hera_qm` repo. Removed tests and updated `__init__.py` accordingly.

### CODE REVIEW

**Comment by SaulAryehKohn** [comment]
This addresses issues #28 and #29

**Comment by jsdillon** [comment]
I don't want to merge this in until the modules are moved to hera_qm. They should be on somebody's master.

**Comment by SaulAryehKohn** [comment]
@jsdillon the modules are already in HERA-Team:hera_qm/dirty_code. The tests still need migrating.

**Comment by SaulAryehKohn** [comment]
@jsdillon tests are migrated.

**Pull request merged**
